name: Arazzo Models Rust Build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - name: Tests
        run: cargo test
        working-directory: arazzo-models
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: 1
      - name: Clippy
        if: runner.os == 'Linux'
        run: cargo clippy
        working-directory: arazzo-models

  musl-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
         docker run --rm --user "$(id -u)":"$(id -g)" -v $(pwd):/workspace -w /workspace/rust -t -e TZ=UTC pactfoundation/rust-musl-build ./scripts/ci-musl-build.sh

  check-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo check --no-default-features
        working-directory: arazzo-models
